/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   init_list.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ejoo-tho <ejoo-tho@student.s19.be>         +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/06/10 14:42:18 by ejoo-tho          #+#    #+#             */
/*   Updated: 2022/07/20 14:54:52 by ejoo-tho         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "checker.h"

/* Here the array of int that was generated by parsing.c is put into a linked
list for stack A. */

t_list	*ft_newnode(int value, int index)
{
	t_list	*newnode;

	newnode = malloc(sizeof(t_list));
	if (!newnode)
		return (NULL);
	newnode->value = value;
	newnode->index = index;
	newnode->chunk = 0;
	newnode->previous = NULL;
	newnode->next = NULL;
	return (newnode);
}

void	ft_addnode_back(t_list **stack, t_list*node)
{
	t_list	*last;

	last = NULL;
	if (!node)
		return ;
	else if (!stack || !(*stack))
		(*stack) = node;
	else
	{
		last = ft_gotolast(stack);
		last->next = node;
		node->previous = last;
	}
}

t_list	*init_list(int *tab, int *size)
{
	t_list	*stack;
	t_list	*node;
	int		i;

	i = 0;
	stack = NULL;
	while (i < *size)
	{
		node = ft_newnode(tab[i], i);
		if (!node)
		{
			ft_freelist(&stack);
			return (NULL);
		}
		ft_addnode_back(&stack, node);
		i++;
	}
	free(tab);
	return (stack);
}
